In [4]:
# Import pands
import pandas as pd

In [6]:
# create pandas series using list
data = [10, 20, 30, 40]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [7]:
# create series using a custom index
data = [1,2,3,4]
i = ['A','B','C','D']
series = pd.Series(data, index=i)
print(series)

A    1
B    2
C    3
D    4
dtype: int64


In [8]:
# create series using dictionary
data = {'a': 10, 'b': 20, 'c': 30}
series = pd.Series(data)
print(series)

a    10
b    20
c    30
dtype: int64


In [9]:
series.replace(20,40)

a    10
b    40
c    30
dtype: int64

In [13]:
# create series using numpy array
import numpy as np
data = np.array([100,200,300])
print(data)

[100 200 300]


In [12]:
# create pandas dataframe from dictionary of lists
import pandas as pd
data = {'Name': ['Alice', 'Bob','Marry'], 'Age': [26,36,46], 'Country':["USA","UK","Aus"]}
df = pd.DataFrame(data)
print(df)

    Name  Age Country
0  Alice   26     USA
1    Bob   36      UK
2  Marry   46     Aus


In [14]:
# create pandas dataframe from numpy array
import  numpy as np
array = np.array([[1,2,3],[4,5,6,],[7,8,9]])
print(array)
df = pd.DataFrame(array, columns=['A','B','C'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
